config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#index'


  resources :posts
  resources :users, only: [:show, :edit, :update, :index]
  resources :comments
  resources :likes
  
  resources :posts do
    resources :likes
  end

  resources :users do
    resources :friendships
    delete 'unfriend', to: 'friendships#destroy'
    post 'receive', to: 'friendships#update'
  end

  get 'requests', to: 'friendships#friend_requests'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true, length: { in: 2..20 }
  validates :last_name, presence: true, length: { in: 2..20 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  mount_uploader :profile_pic, AvatarUploader

  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.confirmed }.compact
  end

  def friends
    friends_array = friendships.map { |friendship| friendship.friend if friendship.confirmed }
    result = friends_array + inverse_friendships.map { |friendship| friendship.user if friendship.confirmed }
    result.compact
  end

  def friend_requests
    inverse_friendships.map { |friendship| friendship.user unless friendship.confirmed }.compact
  end

  def friend?(friend)
    friends = Friendship.where(user: self, friend: friend, confirmed: true) +
              Friendship.where(user: friend, friend: self, confirmed: true)
    friends.any?
  end

  def request(friend)
    Friendship.create(user_id: id, friend_id: friend.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]

      full_name = auth.info.name.split
      user.first_name = full_name.first
      user.last_name = full_name.last
      user.profile_pic = auth.info.image
      # user.first_name = auth.info.first_name
      # user.last_name = auth.info.last_name
      # user.profile_pic = auth.info.profile_pic
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
      if data
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    # @user = User.find_by(email: @fb_user.email)
    if (user = User.find_by(email: @user.email))
      @user = user
    end

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update index]
  before_action :check_authorization, only: %i[edit update]
  before_action :set_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:danger] = 'Wrong date'
      render_to :edit
    end
  end

  private

  def check_authorization
    redirect_to root_path unless current_user.id == params[:id].to_i
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :profile_pic)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def avatar_for(user)
    if user.profile_pic?
      image_tag user.profile_pic.url(:thumb)
    else
      image_tag 'index.png'
    end
  end
end

app/views/users/edit.html.erb
<h1> Edit Profile </h1>

<%= form_for(@user, html: {multipart: true} ) do |f|%>
    <%=f.label :first_name, class: "form-control-md" %><br>
    <%= f.text_field :first_name, class: "form-control-md" %><br><br>
    <%=f.label :last_name, class: "form-control-md"%><br>
    <%= f.text_field :last_name, class: "form-control-md" %><br><br>
    
    <%= f.file_field :profile_pic, class: "form-group" %><br>
    <%= f.submit "Save changes"%>
<%end%>

app/views/users/index.html.erb
<div class="card" style="width: 18rem;">
<div class="card-body">
<% @users.each do |user| %>
  <%if user.id != current_user.id%>
    <li><%= link_to "Check profile", user_path(user) %></li>
    <%= user.first_name %>
    <%= user.last_name %><br>
    <%= user.profile_pic %>
    <br>
    <%if current_user.friend?(user)%>
     <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            You are friends
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= button_to 'Delete Friend', user_unfriend_path(user), method: :delete, class: 'btn-danger'%>
          </div>
        </div>
 
    <%elsif current_user.pending_friends.include?(user)%>
         <%= button_to  user_unfriend_path(user), method: :delete , class:"btn btn-danger btn-sm" do %>
              <i class="fa fa-times"> Cancel Request</i>
            <%end%>
    <%elsif current_user.friend_requests.include?(user)%>
          <%= button_to 'Accept', user_receive_path(user), class: 'btn btn-primary mr-2'%><br>
          <%= button_to 'Reject', user_unfriend_path(user), method: :delete, class: 'btn btn-danger'%>
    <%else%>
      <%= button_to  user_friendships_path(user), class:"btn btn-default btn-sm" do %>
        <i class="fas fa-user-plus"> Add friend</i>
      <%end%>
    <%end%>
    <hr>
  <%end%>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="col-md-12">
        <section class="user-info">
            <%= avatar_for(@user) %>
            <h3 class="margin">
              <%= @user.first_name %>
              <%= @user.last_name%>
            </h3>
        </section>
        <%if @user.id == current_user.id%>
        <div class="anchor-time">
        <%= link_to "Edit profile", edit_user_path(@user)%>
        </div><br>
        <%else%>
          <br>
          <%if current_user.friend?(@user)%>
            <div class=" dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    You are friends
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= button_to 'Delete Friend', user_unfriend_path(@user), method: :delete, class: ' btn-danger'%>
                  </div>
            </div>
  
          <%elsif current_user.pending_friends.include?(@user)%>
              <%= button_to  user_unfriend_path(@user), method: :delete , class:"   btn btn-danger" do %>
                    <i class="fa fa-times"> Cancel Request</i>
                  <%end%>
          <%elsif current_user.friend_requests.include?(@user)%>
                <%= button_to 'Accept', user_receive_path(@user), class: ' btn btn-primary mr-2'%>
                <%= button_to 'Reject', user_unfriend_path(@user), method: :delete, class: ' btn btn-danger'%>
          <%else%>
            <%= button_to  user_friendships_path(@user), class:"   btn btn-default" do %>
              <i class="fas fa-user-plus">Add friend</i>
            <%end%>
          <%end%>
        <%end%>
        <br>

<% @user.posts.each do |p| %>
  <div class="row">
	  <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
               <section class="post-heading">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="media">
                              <div class="media-body">
                                <div class="anchor-username"> 
                                  <h4 class="media-heading"><%= p.user.first_name %></h4>
                                </div>
                                <p class="anchor-time"><%= time_ago_in_words(p.created_at) %> ago</p>
                              </div>
                              <div class="anchor-time">
                                <%if current_user?(p.user)%>
                                  <%= link_to  "Edit", edit_post_path(p) %>
                                  <%= link_to  "Delete", p, method: :delete, data: { confirm: "You sure?" } %>
                                  <br> <br>
                                <%end%>
                              </div>
                            </div>
                        </div>
                    </div>             
               </section>
               <section class="post-body">
                   <p><%= p.content %></p>
               </section>
               <section class="post-footer">
                   <div class="post-footer-option container">
                        <ul class="list-unstyled">
                            <% pre_like = p.likes.find { |like| like.user_id == current_user.id} %>
                            <% if pre_like %>
                            <li><%= button_to  post_like_path(p, pre_like), method: :delete, class:"btn btn-default" do %>
                              <i class="glyphicon glyphicon-thumbs-down"> </i> Unlike</li>
                            <%end%>
                            <% else %>
                            <li><%= button_to  post_likes_path(p), method: :post, class:"btn btn-default" do%>
                              <i class="glyphicon glyphicon-thumbs-up"> </i> Like</li>
                              <%end%>
                            <% end %>
                            <li class="counter"><%= p.likes.count %> <%= (p.likes.count) == 1 ? 'Like' : 'Likes'%></li> 
                        </ul>
                   </div>
                   <hr>
                   <% p.comments.each do |comment| %>
                   <div class="post-footer-comment-wrapper">
                       <div class="comment-form">
                           
                       </div>
                       <div class="comment">
                            <div class="media">
                              <div class="media-body">
                                <div class="anchor-username"><h4 class="media-heading"><%= comment.user.first_name%></h4><div> 
                                <p class="anchor-time"><%= time_ago_in_words(comment.created_at) %> ago</p>
                              </div>
                              <div class="anchor-time">
                              <%if current_user?(comment.user) %>
                              <%= link_to "Edit", edit_comment_path(comment)%>
                              <%= link_to  "Delete", comment, method: :delete, data: { confirm: "You sure?" } %>
                            <%elsif current_user.id != comment.user && current_user.id == p.user_id %>
                              <%= link_to  "Delete", comment, method: :delete, data: { confirm: "You sure?" } %>
                            <%end%>
                            </div> <br>
                              <section class="post-body">
                                <p><%= comment.comment %></p>
                              </section>
                            </div>
                       </div>
                       <hr>
                   </div>
                   <% end %>
               </section>
            </div>
        </div>
      </div>  
    </div>
<% end  %>