config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#index'


  resources :posts
  resources :users, only: [:show, :edit, :update, :index]
  resources :comments
  resources :likes
  
  resources :posts do
    resources :likes
  end

  resources :users do
    resources :friendships
    delete 'unfriend', to: 'friendships#destroy'
    post 'receive', to: 'friendships#update'
  end

  get 'requests', to: 'friendships#friend_requests'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid navigation">
    <div class="navbar-left navigation-left">
      <h2><%= link_to 'FACEBOOK', root_path, class: "face-link" %></h2>
    </div>
    <%if user_signed_in?%>
      <ul class="nav navbar-nav navbar-right header">
       <li><p class="margin-top"><%= link_to "All Users", users_path, class: "face-link" %></p></li>
       <li id="friend-request"><p class="margin-top face-link"><%= link_to "Friend Requests", requests_path(user_id: current_user.id), class: "face-link" %> <%= current_user.friend_requests.count%></p></li>
         <li class="dropdown">
            <p class="face-link margin-top-2 dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </p>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Friends",  user_friendships_path(current_user) %></li>
              <li><%= link_to "Settings",  edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
    <%else%>
      <div class="navbar-right">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="navigation-right">
          <div class="field">
            <%= f.label :email, class: "label" %><br />
            <%= f.email_field :email,  autofocus: true, autocomplete: "email", class: "input" %>
          </div>

          <div class="field input-field">
            <%= f.label :password, class: "label" %><br />
            <%= f.password_field :password, autocomplete: "current-password", class: "input" %>
          </div>

          <div class="actions">
            <%= f.submit "Log in", class: "button" %>
          </div>
      <% end %>
    <%end%>
     </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
        <% flash.each do |message_type, message|%>
          <%= content_tag(:div,  message, class: "alert alert-#{message_type}")%>
        <%end%>
        <%=yield%>
    </div>
  </body>
</html>